// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkqzmubtxwbgniuesmdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcXptdWJ0eHdiZ25pdWVzbWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTc5NDcsImV4cCI6MjA2NTI5Mzk0N30.V7h8ZtEHJso_wP0x56M3Q9AhBjGkOvQ9oTiwW0coc9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);